spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/estudos-spring
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      show-sql: true
      format-sql: true
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
      dialect: org.hibernate.dialect.MariaDBDialect


