spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    testWhileIdle: true
    validationQuery: SELECT 1
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      show-sql: true
      format-sql: true
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
      dialect: org.hibernate.dialect.MariaDBDialect


